/- Generated by Lem from probe_capture.lem. -/

import LemLib

import LemLib.Pervasives_extra
import LemLib.Pervasives
import LemLib.Bridges
open Lem_Num
open Lem_Pervasives
open Lem_List
open Lem_Set
open Lem_Basic_classes
open Lem_Bool
open Lem_Tuple
open Lem_Maybe
open Lem_Either
open Lem_Function
open Lem_Map
open Lem_String
open Lem_Word
open Lem_Show
open Lem_Sorting
open Lem_Relation
open Lem_Pervasives_extra
open Lem_Set_helpers
open Lem_Function_extra
open Lem_Maybe_extra
open Lem_Map_extra
open Lem_Num_extra
open Lem_Set_extra
open Lem_List_extra
open Lem_String_extra
open Lem_Assert_extra
open Lem_Show_extra
open Lem_Machine_word

/- removed value specification -/

def  capture_probe  (x : Option (Option (Nat)))  : Option (Nat) :=  match  x with  |  some  none1 =>  none |  none =>  none

def  capture_result   : Option (Nat) :=  capture_probe  (some  (some (  5)))
