/- Generated by Lem from probe_fuel_shadow.lem. -/

import LemLib

import LemLib.Pervasives_extra
import LemLib.Pervasives
import LemLib.Bridges
open Lem_Num
open Lem_Pervasives
open Lem_List
open Lem_Set
open Lem_Basic_classes
open Lem_Bool
open Lem_Tuple
open Lem_Maybe
open Lem_Either
open Lem_Function
open Lem_Map
open Lem_String
open Lem_Word
open Lem_Show
open Lem_Sorting
open Lem_Relation
open Lem_Pervasives_extra
open Lem_Set_helpers
open Lem_Function_extra
open Lem_Maybe_extra
open Lem_Map_extra
open Lem_Num_extra
open Lem_Set_extra
open Lem_List_extra
open Lem_String_extra
open Lem_Assert_extra
open Lem_Show_extra
open Lem_Machine_word

/- removed value specification -/

 def  shadow_probe_lemFuel (lemFuel : Nat)  (lemFuel : Nat) (n : Nat)  : Nat := match lemFuel with
  | 0 => (999)
  | Nat.succ lemFuel => (
  if  n  ==   0 then  lemFuel  else (shadow_probe_lemFuel lemFuel)  lemFuel  (n  -   1))

def shadow_probe : Nat → Nat → Nat := shadow_probe_lemFuel lemDefaultFuel

def  shadow_result   : Nat :=  shadow_probe (  0) (  3)
