/- Generated by Lem from assert_extra.lem. -/

import LemLib


namespace Lem_Assert_extra





/- removed value specification -/

/- removed value specification -/

def  fail  {a : Type}   : a :=  failwith  "fail"
/- removed value specification -/

def  ensure  (test : Bool) (msg : String)  : Unit := 
  if  test then 
    ()
   else (failwithI  msg : Unit)

end Lem_Assert_extra

