/- Generated by Lem from assert_extra.lem. -/

import LemLib

set_option compiler.extract_closed false

namespace Lem_Assert_extra





/- removed value specification -/

/- removed value specification -/

@[never_extract] def  fail  {a : Type} [Inhabited a]   : a := (failwithI  "fail" : a)
/- removed value specification -/

def  ensure  (test : Bool) (msg : String)  : Unit := 
  if  test then 
    ()
   else (failwithI  msg : Unit)

end Lem_Assert_extra

