/- Generated by Lem from debug.lem. -/

import LemLib

set_option compiler.extract_closed false

namespace Lem_Debug

/- removed value specification -/

/- removed value specification -/

end Lem_Debug

