/- Generated by Lem from function.lem. -/

import LemLib

import LemLib.Bool
import LemLib.Basic_classes

namespace Lem_Function
/- **************************************************************************** -/
/- A library for common operations on functions                               -/
/- **************************************************************************** -/

open Lem_Bool
open Lem_Basic_classes

/- ----------------------- -/
/- identity function       -/
/- ----------------------- -/

/- lem: replaced by its target representation: 
def  id  {a : Type}  (x : a)  : a :=  x -/
/- ----------------------- -/
/- constant function       -/
/- ----------------------- -/

/- No Lean target_rep: Lean's Function.const has different argument conventions
   (first explicit param is a type, not a value). The universal inline on line 29
   handles Lean correctly by inlining const x y = x at call sites. -/

/- ----------------------- -/
/- function composition    -/
/- ----------------------- -/

/- lem: replaced by its target representation: 
def  comb  {a b c : Type}  (f : b → c) (g : a → b)  : a → c :=  (fun (x : a) =>  f  (g  x)) -/
/- ----------------------- -/
/- function application    -/
/- ----------------------- -/

/- lem: replaced by its target representation: 
def  apply  {a b : Type}  (f : a → b)  : a → b :=  (fun (x : a) =>  f  x) -/
def rev_apply {a b : Type} (x : a) (f : a → b) : b := f x
/- ----------------------- -/
/- flipping argument order -/
/- ----------------------- -/

/- lem: replaced by its target representation: 
def  flip  {a b c : Type}  (f : a → b → c)  : b → a → c :=  (fun (x : b) (y : a) =>  f  y  x) -/
/- currying / uncurrying -/

def curry {a b c : Type} (f : (a × b) → c) : a → b → c := (fun (a1 : a) (b1 : b) => f (a1, b1))
def uncurry {a b c : Type} (f : a → b → c) (p : (a × b)) : c := match f, p with | f, (a1, b1) => f a1 b1
end Lem_Function
