/- Generated by Lem from list.lem. -/

import LemLib

import LemLib.Bool
import LemLib.Maybe
import LemLib.Basic_classes
import LemLib.Function
import LemLib.Tuple
import LemLib.Num

namespace Lem_List
 /- **************************************************************************** -/
/- A library for lists                                                        -/
/-                                                                            -/
/- It mainly follows the Haskell List-library                                 -/
/- **************************************************************************** -/
/- ========================================================================== -/
/- Header                                                                     -/
/- ========================================================================== -/

open Lem_Bool
open Lem_Maybe
open Lem_Basic_classes
open Lem_Function
open Lem_Tuple
open Lem_Num

/- ========================================================================== -/
/- Basic list functions                                                       -/
/- ========================================================================== -/
/- The type of lists as well as list literals like [], [1;2], ... are hardcoded.
   Thus, we can directly dive into derived definitions. -/

/- ----------------------- -/
/- cons                    -/
/- ----------------------- -/

/- ----------------------- -/
/- Emptyness check         -/
/- ----------------------- -/

/- lem: replaced by its target representation: 
def  null  {a : Type}  (l : List a)  : Bool :=  match  l with |  [] =>  true |  _ =>  false  -/
/- ----------------------- -/
/- Length                  -/
/- ----------------------- -/

/- lem: replaced by its target representation: 
 def  length  {a : Type}  (l : List a)  : Nat := 
  match  l with  |  [] =>  0 |  x  ::  xs =>  List.length  xs  +  1
   -/
/- ----------------------- -/
/- Equality                -/
/- ----------------------- -/

/- lem: replaced by its target representation: 

 def  listEqualBy  {a : Type}  (eq : a → a → Bool) (l1 : List a) (l2 : List a)  : Bool :=  match l1, l2 with  | [],  [] =>  true | [], ( _ :: _) =>  false | (_ :: _),  [] =>  false | x :: xs,  y  ::  ys =>  (eq  x  y  &&  listEqualBy  eq  xs  ys)
 -/

instance (a : Type) [Eq0 a] : Eq0 (List  a) where

    isEqual   :=  (listEqualBy  (fun x y => x == y))

    isInequal   l1  l2  :=  not  ((listEqualBy  (fun x y => x == y)  l1  l2))

/- ----------------------- -/
/- compare                 -/
/- ----------------------- -/

 def  lexicographicCompareBy  {a : Type}  (cmp : a → a → LemOrdering) (l1 : List a) (l2 : List a)  : LemOrdering :=  match l1, l2 with  | [],  [] =>  LemOrdering.EQ | [],  _ :: _ =>  LemOrdering.LT | _ :: _,  [] =>  LemOrdering.GT | x :: xs,  y :: ys =>  (       match  cmp  x  y with  |  LemOrdering.LT =>  LemOrdering.LT |  LemOrdering.GT =>  LemOrdering.GT |  LemOrdering.EQ =>  lexicographicCompareBy  cmp  xs  ys            )

 def  lexicographicLessBy  {a : Type}  (less : a → a → Bool) (less_eq : a → a → Bool) (l1 : List a) (l2 : List a)  : Bool :=  match l1, l2 with  | [],  [] =>  false | [],  _ :: _ =>  true | _ :: _,  [] =>  false | x :: xs,  y :: ys =>  ((less  x  y)  ||  ((less_eq  x  y)  &&  (lexicographicLessBy  less  less_eq  xs  ys)))

 def  lexicographicLessEqBy  {a : Type}  (less : a → a → Bool) (less_eq : a → a → Bool) (l1 : List a) (l2 : List a)  : Bool :=  match l1, l2 with  | [],  [] =>  true | [],  _ :: _ =>  true | _ :: _,  [] =>  false | x :: xs,  y :: ys =>  (less  x  y  ||  (less_eq  x  y  &&  lexicographicLessEqBy  less  less_eq  xs  ys))

instance (a : Type) [Ord0 a] : Ord0 (List  a) where

    compare   :=  (lexicographicCompareBy  Ord0.compare)

    isLess   :=  (lexicographicLessBy  isLess  isLessEqual)

    isLessEqual   :=  (lexicographicLessEqBy  isLess  isLessEqual)

    isGreater   x  y  :=  (lexicographicLessBy  isLess  isLessEqual  y  x)

    isGreaterEqual   x  y  :=  (lexicographicLessEqBy  isLess  isLessEqual  y  x)

/- ----------------------- -/
/- Append                  -/
/- ----------------------- -/

/- lem: replaced by its target representation:  /- originally append -/
 def  append  {a : Type}  (xs : List a) (ys : List a)  : List a :=  match  xs with  |  [] =>  ys |  x  ::  xs' =>  x  ::  (xs'  ++  ys)
                    -/
/- ----------------------- -/
/- snoc                    -/
/- ----------------------- -/

def  snoc  {a : Type}  (e : a) (l : List a)  : List a :=  l  ++  [e]
/- ----------------------- -/
/- Reverse                 -/
/- ----------------------- -/
/- First lets define the function [reverse_append], which is
   closely related to reverse. [reverse_append l1 l2] appends the list [l2] to the reverse of [l1].
   This can be implemented more efficienctly than appending and is
   used to implement reverse. -/

/- lem: replaced by its target representation:  /- originally named rev_append -/
 def  reverseAppend  {a : Type}  (l1 : List a) (l2 : List a)  : List a :=  match  l1 with  |  [] =>  l2 |  x  ::  xs =>  List.reverseAux  xs  (x  ::  l2)
                                -/
/- Reversing a list -/

/- lem: replaced by its target representation:  /- originally named rev -/
def  reverse  {a : Type}  (l : List a)  : List a :=  List.reverseAux  l  [] -/
/- ----------------------- -/
/- Map                     -/
/- ----------------------- -/

 def  map_tr  {a : Type} {b : Type}  (rev_acc : List b) (f : a → b) (l : List a)  : List b :=  match  l with  |  [] =>  List.reverse  rev_acc |  x  ::  xs =>  map_tr  ((f  x)  ::  rev_acc)  f  xs

/- taken from: https://blogs.janestreet.com/optimizing-list-map/ -/

 def  count_map  {a : Type} {b : Type}  (f : a → b) (l : List a) (ctr : Nat)  : List b :=
  match  l with  |  [] =>  [] |  hd  ::  tl =>  f  hd  ::       (lem_if  natLtb  ctr (  5000) then  count_map  f  tl  (ctr  +   1)       else  map_tr  []  f  tl)

/- lem: replaced by its target representation: 
def  map  {a : Type} {b : Type}  (f : a → b) (l : List a)  : List b :=  count_map  f  l  0 -/
/- * DPM: for standard List.map replace line below, otherwise uses imperative
  * version supplied with Lem to avoid blowing stack on huge lists.
  * SRK: don't bother using standard List.map, because long lists really do happen.
  -/
/- declare ocaml    target_rep function map = `List.map` -/

/- ----------------------- -/
/- Reverse Map             -/
/- ----------------------- -/

/- ========================================================================== -/
/- Folding                                                                    -/
/- ========================================================================== -/
/- ----------------------- -/
/- fold left               -/
/- ----------------------- -/

/- lem: replaced by its target representation:  /- originally foldl -/

 def  foldl  {a : Type} {b : Type}  (f : a → b → a) (b : a) (l : List b)  : a :=  match  l with  |  [] =>  b |  x  ::  xs =>  List.foldl  f  (f  b  x)  xs
 -/
/- ----------------------- -/
/- fold right              -/
/- ----------------------- -/

/- lem: replaced by its target representation:  /- originally foldr with different argument order -/
 def  foldr  {a : Type} {b : Type}  (f : a → b → b) (b : b) (l : List a)  : b :=  match  l with  |  [] =>  b |  x  ::  xs =>  f  x  (lemListFoldr  f  b  xs)
 -/
/- ----------------------- -/
/- concatenating lists     -/
/- ----------------------- -/

/- lem: replaced by its target representation:  /- before also called "flatten" -/
def  concat  {a : Type}   : List (List a) → List a :=  lemListFoldr  (fun x y => x ++ y)  [] -/
/- -------------------------- -/
/- concatenating with mapping -/
/- -------------------------- -/

/- ------------------------- -/
/- universal qualification   -/
/- ------------------------- -/

/- lem: replaced by its target representation:  /- originally for_all -/
def  all  {a : Type}  (P : a → Bool) (l : List a)  : Bool :=  List.foldl  (fun (r : Bool) (e : a) =>  P  e  &&  r)  true  l -/
/- ------------------------- -/
/- existential qualification -/
/- ------------------------- -/

/- lem: replaced by its target representation:  /- originally exist -/
def  any  {a : Type}  (P : a → Bool) (l : List a)  : Bool :=  List.foldl  (fun (r : Bool) (e : a) =>  P  e  ||  r)  false  l -/
/- ------------------------- -/
/- dest_init                 -/
/- ------------------------- -/
/- get the initial part and the last element of the list in a safe way -/

 def  dest_init_aux  {a : Type}  (rev_init : List a) (last_elem_seen : a) (to_process : List a)  : (List a ×a) :=
  match  to_process with  |  [] =>  (List.reverse  rev_init, last_elem_seen) |  x :: xs =>  dest_init_aux  (last_elem_seen :: rev_init)  x  xs

def  dest_init  {a : Type}  (l : List a)  : Option ((List a ×a)) :=  match  l with  |  [] =>  none |  x :: xs =>  some  (dest_init_aux  []  x  xs)

/- ========================================================================== -/
/- Indexing lists                                                             -/
/- ========================================================================== -/
/- ------------------------- -/
/- index / nth with maybe   -/
/- ------------------------- -/

/- lem: replaced by its target representation: 

 def  index  {a : Type}  (l : List a) (n : Nat)  : Option a :=  match  l with  |  [] =>  none |  x  ::  xs => ( lem_if  n  =  0 then  some  x  else  listGetOpt  xs  (n - 1))
 -/
/- ------------------------- -/
/- findIndices               -/
/- ------------------------- -/
/- [findIndices P l] returns the indices of all elements of list [l] that satisfy predicate [P]. 
   Counting starts with 0, the result list is sorted ascendingly -/

 def  findIndices_aux  {a : Type}   (i :Nat) (P : a → Bool) (l : List a)  : List (Nat) :=
  match  l with  |  [] =>  ([] : List (Nat)) |  x  ::  xs => ( lem_if  P  x then  i  ::  findIndices_aux  (i  +   1)  P  xs  else  findIndices_aux  (i  +   1)  P  xs)

def  findIndices  {a : Type}  (P : a → Bool) (l : List a)  : List (Nat) :=  findIndices_aux (  0)  P  l
/- ------------------------- -/
/- findIndex                 -/
/- ------------------------- -/
/- findIndex returns the first index of a list that satisfies a given predicate. -/

def  findIndex  {a : Type}  (P : a → Bool) (l : List a)  : Option (Nat) :=  match  findIndices  P  l with  |  [] =>  none |  x  ::  _ =>  some  x

/- ------------------------- -/
/- elemIndices               -/
/- ------------------------- -/

/- ------------------------- -/
/- elemIndex                 -/
/- ------------------------- -/

/- ========================================================================== -/
/- Creating lists                                                             -/
/- ========================================================================== -/
/- ------------------------- -/
/- genlist                   -/
/- ------------------------- -/
/- [genlist f n] generates the list [f 1; ... (f (n-1))] -/

/- lem: replaced by its target representation: 


 def  genlist  {a : Type}  (f : Nat → a)  (n  : Nat)  : List a := 
  match  (n :  Nat) with  |  (0 : Nat) =>  [] |  (n' + 1) =>  snoc  (f  n')  (List.map  f  (List.range  n'))
   -/
/- ------------------------- -/
/- replicate                 -/
/- ------------------------- -/

/- lem: replaced by its target representation: 
 def  replicate  {a : Type}  (n : Nat) (x : a)  : List a := 
  match  n with  |  0 =>  [] |  (n' + 1) =>  x  ::  List.replicate  n'  x
   -/
/- ========================================================================== -/
/- Sublists                                                                   -/
/- ========================================================================== -/
/- ------------------------- -/
/- splitAt                   -/
/- ------------------------- -/
/- [splitAt n xs] returns a tuple (xs1, xs2), with "append xs1 xs2 = xs" and 
   "length xs1 = n". If there are not enough elements 
   in [xs], the original list and the empty one are returned. -/

 def  splitAtAcc  {a : Type}  (revAcc : List a) (n : Nat) (l : List a)  : (List a ×List a) :=
  match  l with  |  [] =>  (List.reverse  revAcc, []) |  x :: xs => ( lem_if  natLteb  n (  0) then  (List.reverse  revAcc, l)  else  splitAtAcc  (x :: revAcc)  (n -   1)  xs)

def  splitAt  {a : Type}  (n : Nat) (l : List a)  : (List a ×List a) :=
   splitAtAcc  []  n  l
/-   match l with
    | []    -> ([], [])
    | x::xs -> 
       if n <= 0 then ([], l) else
       begin
         let (l1, l2) = splitAt (n-1) xs in
         (x::l1, l2)
       end
    end -/

/- ------------------------- -/
/- take                      -/
/- ------------------------- -/
/- take n xs returns the prefix of xs of length n, or xs itself if n > length xs -/

/- lem: replaced by its target representation: 
def  take  {a : Type}  (n : Nat) (l : List a)  : List a :=  Prod.fst  (splitAt  n  l) -/
/- ------------------------- -/
/- drop                      -/
/- ------------------------- -/
/- [drop n xs] drops the first [n] elements of [xs]. It returns the empty list, if [n] > [length xs]. -/

/- lem: replaced by its target representation: 
def  drop  {a : Type}  (n : Nat) (l : List a)  : List a :=  Prod.snd  (splitAt  n  l) -/
/- ------------------------------------ -/
/- splitWhile, takeWhile, and dropWhile -/
/- ------------------------------------ -/

 def  splitWhile_tr  {a : Type}  (p : a → Bool) (xs : List a) (acc : List a)  : (List a ×List a) :=  match  xs with  |  [] =>      (List.reverse  acc, []) |  x :: xs => (     lem_if  p  x then        splitWhile_tr  p  xs  (x :: acc)      else        (List.reverse  acc, (x :: xs)))

def  splitWhile  {a : Type}  (p : a → Bool) (xs : List a)  : (List a ×List a) :=  splitWhile_tr  p  xs  []
/- [takeWhile p xs] takes the first elements of [xs] that satisfy [p]. -/

def  takeWhile  {a : Type}  (p : a → Bool) (l : List a)  : List a :=  Prod.fst  (splitWhile  p  l)
/- [dropWhile p xs] drops the first elements of [xs] that satisfy [p]. -/

def  dropWhile  {a : Type}  (p : a → Bool) (l : List a)  : List a :=  Prod.snd  (splitWhile  p  l)
/- ------------------------- -/
/- isPrefixOf                -/
/- ------------------------- -/

 def  isPrefixOf  {a : Type} [Eq0 a]  (l1 : List a) (l2 : List a)  : Bool :=  match l1,  l2 with  | [],  _ =>  true | _ :: _,  [] =>  false | x :: xs,  y :: ys =>  (x  ==  y)  &&  isPrefixOf  xs  ys

/- ------------------------- -/
/- update                    -/
/- ------------------------- -/

/- lem: replaced by its target representation: 
 def  update  {a : Type}  (l : List a) (n : Nat) (e : a)  : List a :=  
  match  l with  |  [] =>  [] |  x  ::  xs => ( lem_if  n  =  0 then  e  ::  xs  else  x  ::  (lemListUpdate  xs  (n  -  1)  e))
 -/
/- ========================================================================== -/
/- Searching lists                                                            -/
/- ========================================================================== -/
/- ------------------------- -/
/- Membership test           -/
/- ------------------------- -/
/- The membership test, one of the basic list functions, is actually tricky for
   Lem, because it is tricky, which equality to use. From Lem`s point of 
   perspective, we want to use the equality provided by the equality type - class.
   This allows for example to check whether a set is in a list of sets.

   However, in order to use the equality type class, elem essentially becomes
   existential quantification over lists. For types, which implement semantic
   equality (=) with syntactic equality, this is overly complicated. In
   our theorem prover backend, we would end up with overly complicated, harder
   to read definitions and some of the automation would be harder to apply.
   Moreover, nearly all the old Lem generated code would change and require 
   (hopefully minor) adaptions of proofs.

   For now, we ignore this problem and just demand, that all instances of
   the equality type class do the right thing for the theorem prover backends.   
-/

/- lem: replaced by its target representation: 

def  elemBy  {a : Type}  (eq : a → a → Bool) (e : a) (l : List a)  : Bool :=  List.any  l  (eq  e) -/
def  elem  {a : Type} [Eq0 a]   : a → List a → Bool :=  listMemberBy  (fun x y => x == y)
/-  declare ocaml    target_rep function elem = `List.mem`  -/

/- ------------------------- -/
/- Find                      -/
/- ------------------------- -/
 /- previously not of maybe type -/
 def  find  {a : Type}  (P : a → Bool) (l : List a)  : Option a :=  match  l with  |  [] =>  none |  x  ::  xs => ( lem_if  P  x then  some  x  else  find  P  xs)

/- ----------------------------- -/
/- Lookup in an associative list -/
/- ----------------------------- -/

/- DPM: eta-expansion for Coq backend type-inference. -/
def  lookupBy  {a : Type} {b : Type}  (eq : a → a → Bool) (k : a) (m : List ((a ×b)))  : Option b :=  Option.map  (fun (x : (a ×b)) =>  Prod.snd  x)  (find  (fun (p : (a ×b)) =>  match p with |  (k',  _) =>  eq  k  k' )  m)

/- ------------------------- -/
/- filter                    -/
/- ------------------------- -/

/- lem: replaced by its target representation: 
 def  filter  {a : Type}  (P : a → Bool) (l : List a)  : List a :=  match  l with  |  [] =>  [] |  x  ::  xs => ( lem_if  (P  x) then  x  ::  (List.filter  P  xs)  else  List.filter  P  xs)
                      -/
/- ------------------------- -/
/- partition                 -/
/- ------------------------- -/

def  partition  {a : Type}  (P : a → Bool) (l : List a)  : (List a ×List a) :=  (List.filter  P  l, List.filter  (fun (x : a) =>  not  (P  x))  l)
def  reversePartition  {a : Type}  (P : a → Bool) (l : List a)  : (List a ×List a) :=  partition  P  (List.reverse  l)
/- ------------------------- -/
/- delete first element      -/
/- with certain property     -/
/- ------------------------- -/

/- lem: replaced by its target representation:  
 def  deleteFirst  {a : Type}  (P : a → Bool) (l : List a)  : Option (List a) :=  match  l with  |  [] =>  none |  x  ::  xs => ( lem_if  (P  x) then  some  xs  else  Option.map  (fun (xs' : List a) =>  x  ::  xs')  (lemListDeleteFirst  P  xs))
                           -/

def  deleteBy  {a : Type}  (eq : a → a → Bool) (x : a) (l : List a)  : List a :=  fromMaybe  l  (lemListDeleteFirst  (eq  x)  l)

/- ========================================================================== -/
/- Zipping and unzipping lists                                                -/
/- ========================================================================== -/
/- ------------------------- -/
/- zip                       -/
/- ------------------------- -/
/- zip takes two lists and returns a list of corresponding pairs. If one input list is short, excess elements of the longer list are discarded. -/

/- lem: replaced by its target representation:  /- before combine -/
 def  zip  {a : Type} {b : Type}  (l1 : List a) (l2 : List b)  : List ((a ×b)) :=  match l1,  l2 with  | x  ::  xs,  y  ::  ys =>  (x, y)  ::  lemListZip  xs  ys | _, _ =>  []
 -/
/- ------------------------- -/
/- unzip                     -/
/- ------------------------- -/

/- lem: replaced by its target representation: 
 def  unzip  {a : Type} {b : Type}  (l : List ((a ×b)))  : (List a ×List b) :=  match  l with  |  [] =>  ([], []) |  (x,  y)  ::  xys => ( let  (xs,  ys)   := lemListUnzip  xys;  (x  ::  xs, y  ::  ys))
 -/

instance (a : Type) [SetType a] : SetType (List  a) where

   setElemCompare   :=  lexicographicCompareBy  (@setElemCompare (a) _)

/- ------------------------- -/
/- distinct elements         -/
/- ------------------------- -/

 def  allDistinct  {a : Type} [Eq0 a]  (l : List a)  : Bool :=
  match  l with  |  [] =>  true | ( x :: l') =>  not  (elem  x  l')  &&  allDistinct  l'

/- some more useful functions -/

 def  mapMaybe  {a : Type} {b : Type}  (f : a → Option b) (xs : List a)  : List b :=
  match  xs with  |  [] =>  [] |  x :: xs => (       match  f  x with  |  none =>  mapMaybe  f  xs |  some  y =>  y  ::  (mapMaybe  f  xs)       )

 def  mapiAux  {a : Type} {b : Type}  (f : Nat → b → a)  (n  : Nat) (l : List b)  : List a :=  match  l with  |  [] =>  [] |  x  ::  xs =>  (f  n  x)  ::  mapiAux  f  (n  +   1)  xs

/- lem: replaced by its target representation: 
def  mapi  {a : Type} {b : Type}  (f : Nat → a → b) (l : List a)  : List b :=  mapiAux  f  0  l -/
def  deletes  {a : Type} [Eq0 a]  (xs : List a) (ys : List a)  : List a :=
  List.foldl  (flip  (deleteBy  (fun x y => x == y)))  xs  ys
/- ========================================================================== -/
/- Comments (not clean yet, please ignore the rest of the file)               -/
/- ========================================================================== -/
/- ----------------------- -/
/- skipped from Haskell Lib -/
/- ----------------------- 

intersperse :: a -> [a] -> [a]
intercalate :: [a] -> [[a]] -> [a]
transpose :: [[a]] -> [[a]]
subsequences :: [a] -> [[a]]
permutations :: [a] -> [[a]]
foldl` :: (a -> b -> a) -> a -> [b] -> aSource
foldl1` :: (a -> a -> a) -> [a] -> aSource

and
or
sum
product
maximum
minimum
scanl
scanr
scanl1
scanr1
Accumulating maps

mapAccumL :: (acc -> x -> (acc, y)) -> acc -> [x] -> (acc, [y])Source
mapAccumR :: (acc -> x -> (acc, y)) -> acc -> [x] -> (acc, [y])Source

iterate :: (a -> a) -> a -> [a]
repeat :: a -> [a]
cycle :: [a] -> [a]
unfoldr


takeWhile :: (a -> Bool) -> [a] -> [a]Source
dropWhile :: (a -> Bool) -> [a] -> [a]Source
dropWhileEnd :: (a -> Bool) -> [a] -> [a]Source
span :: (a -> Bool) -> [a] -> ([a], [a])Source
break :: (a -> Bool) -> [a] -> ([a], [a])Source
break p is equivalent to span (not . p).
stripPrefix :: Eq a => [a] -> [a] -> Maybe [a]Source
group :: Eq a => [a] -> [[a]]Source
inits :: [a] -> [[a]]Source
tails :: [a] -> [[a]]Source


isPrefixOf :: Eq a => [a] -> [a] -> BoolSource
isSuffixOf :: Eq a => [a] -> [a] -> BoolSource
isInfixOf :: Eq a => [a] -> [a] -> BoolSource



notElem :: Eq a => a -> [a] -> BoolSource

zip3 :: [a] -> [b] -> [c] -> [(a, b, c)]Source
zip4 :: [a] -> [b] -> [c] -> [d] -> [(a, b, c, d)]Source
zip5 :: [a] -> [b] -> [c] -> [d] -> [e] -> [(a, b, c, d, e)]Source
zip6 :: [a] -> [b] -> [c] -> [d] -> [e] -> [f] -> [(a, b, c, d, e, f)]Source
zip7 :: [a] -> [b] -> [c] -> [d] -> [e] -> [f] -> [g] -> [(a, b, c, d, e, f, g)]Source

zipWith :: (a -> b -> c) -> [a] -> [b] -> [c]Source
zipWith3 :: (a -> b -> c -> d) -> [a] -> [b] -> [c] -> [d]Source
zipWith4 :: (a -> b -> c -> d -> e) -> [a] -> [b] -> [c] -> [d] -> [e]Source
zipWith5 :: (a -> b -> c -> d -> e -> f) -> [a] -> [b] -> [c] -> [d] -> [e] -> [f]Source
zipWith6 :: (a -> b -> c -> d -> e -> f -> g) -> [a] -> [b] -> [c] -> [d] -> [e] -> [f] -> [g]Source
zipWith7 :: (a -> b -> c -> d -> e -> f -> g -> h) -> [a] -> [b] -> [c] -> [d] -> [e] -> [f] -> [g] -> [h]Source


unzip3 :: [(a, b, c)] -> ([a], [b], [c])Source
unzip4 :: [(a, b, c, d)] -> ([a], [b], [c], [d])Source
unzip5 :: [(a, b, c, d, e)] -> ([a], [b], [c], [d], [e])Source
unzip6 :: [(a, b, c, d, e, f)] -> ([a], [b], [c], [d], [e], [f])Source
unzip7 :: [(a, b, c, d, e, f, g)] -> ([a], [b], [c], [d], [e], [f], [g])Source


lines :: String -> [String]Source
words :: String -> [String]Source
unlines :: [String] -> StringSource
unwords :: [String] -> StringSource
nub :: Eq a => [a] -> [a]Source
delete :: Eq a => a -> [a] -> [a]Source

(\\) :: Eq a => [a] -> [a] -> [a]Source
union :: Eq a => [a] -> [a] -> [a]Source
intersect :: Eq a => [a] -> [a] -> [a]Source
sort :: Ord a => [a] -> [a]Source
insert :: Ord a => a -> [a] -> [a]Source


nubBy :: (a -> a -> Bool) -> [a] -> [a]Source
deleteBy :: (a -> a -> Bool) -> a -> [a] -> [a]Source
deleteFirstsBy :: (a -> a -> Bool) -> [a] -> [a] -> [a]Source
unionBy :: (a -> a -> Bool) -> [a] -> [a] -> [a]Source
intersectBy :: (a -> a -> Bool) -> [a] -> [a] -> [a]Source
groupBy :: (a -> a -> Bool) -> [a] -> [[a]]Source
sortBy :: (a -> a -> Ordering) -> [a] -> [a]Source
insertBy :: (a -> a -> Ordering) -> a -> [a] -> [a]Source
maximumBy :: (a -> a -> Ordering) -> [a] -> aSource
minimumBy :: (a -> a -> Ordering) -> [a] -> aSource
genericLength :: Num i => [b] -> iSource
genericTake :: Integral i => i -> [a] -> [a]Source
genericDrop :: Integral i => i -> [a] -> [a]Source
genericSplitAt :: Integral i => i -> [b] -> ([b], [b])Source
genericIndex :: Integral a => [b] -> a -> bSource
genericReplicate :: Integral i => i -> a -> [a]Source


-/
/- ----------------------- -/
/- skipped from Lem Lib    -/
/- ----------------------- 


val for_all2 : forall 'a 'b. ('a -> 'b -> bool) -> list 'a -> list 'b -> bool
val exists2 : forall 'a 'b. ('a -> 'b -> bool) -> list 'a -> list 'b -> bool
val map2 : forall 'a 'b 'c. ('a -> 'b -> 'c) -> list 'a -> list 'b -> list 'c 
val rev_map2 : forall 'a 'b 'c. ('a -> 'b -> 'c) -> list 'a -> list 'b -> list 'c
val fold_left2 : forall 'a 'b 'c. ('a -> 'b -> 'c -> 'a) -> 'a -> list 'b -> list 'c -> 'a
val fold_right2 : forall 'a 'b 'c. ('a -> 'b -> 'c -> 'c) -> list 'a -> list 'b -> 'c -> 'c


/ - now maybe result and called lookup - /
val assoc : forall 'a 'b. 'a -> list ('a * 'b) -> 'b
let inline {ocaml} assoc = Ocaml.List.assoc


val mem_assoc : forall 'a 'b. 'a -> list ('a * 'b) -> bool
val remove_assoc : forall 'a 'b. 'a -> list ('a * 'b) -> list ('a * 'b)



val stable_sort : forall 'a. ('a -> 'a -> num) -> list 'a -> list 'a
val fast_sort : forall 'a. ('a -> 'a -> num) -> list 'a -> list 'a

val merge : forall 'a. ('a -> 'a -> num) -> list 'a -> list 'a -> list 'a
val intersect : forall 'a. list 'a -> list 'a -> list 'a


-/

/- lem: replaced by its target representation: 
 def  catMaybes  {a : Type}  (xs : List (Option a))  : List a := 
  match  xs with  |  [] =>          [] | ( none  ::  xs') =>          lemListCatMaybes  xs' | ( some  x  ::  xs') =>          x  ::  lemListCatMaybes  xs'
   -/
end Lem_List
