/- Generated by Lem from maybe_extra.lem. -/

import LemLib

import LemLib.Basic_classes
import LemLib.Maybe
import LemLib.Assert_extra

namespace Lem_Maybe_extra
 /- **************************************************************************** -/
/- extra functions for maybe / option                                         -/
/-                                                                            -/
/- **************************************************************************** -/

open Lem_Basic_classes
open Lem_Maybe
open Lem_Assert_extra

/- ----------------------- -/
/- fromJust                -/
/- ----------------------- -/

def fromJust { a : Type } [Inhabited a] (op : Option a) : a :=
  match op with
  | some v => v
  | none => (failwithI "fromJust of Nothing" : a)
/- Lean: at call sites with a ground result type, emit the
   [Inhabited]-bounded LemLib.fromJustI instead (axiom-free failure leaf;
   success equation still holds by rfl). Type-variable sites keep this
   generated fromJust — no constraint propagation. -/

end Lem_Maybe_extra
