/- Generated by Lem from maybe_extra.lem. -/

import LemLib

import LemLib.Basic_classes
import LemLib.Maybe
import LemLib.Assert_extra

namespace Lem_Maybe_extra
 

open Lem_Basic_classes
open Lem_Maybe
open Lem_Assert_extra

/- removed value specification -/

def  fromJust  {a : Type} [Inhabited a]  (op : Option a)  : a :=  match  op with  |  some  v =>  v |  none => (failwithI  "fromJust of Nothing" : a) 
end Lem_Maybe_extra


