/- Generated by Lem from num.lem. -/

import LemLib

import LemLib.Bool
import LemLib.Basic_classes

namespace Lem_Num


open Lem_Bool
open Lem_Basic_classes




/- 

 -/

/-  ==========================================================================  -/
/-  Syntactic type-classes for common operations                                -/
/-  ==========================================================================  -/

/-  Typeclasses can be used as a mean to overload constants like "+", "-", etc  -/

class NumNegate (a : Type) where 
 
  numNegate :  a →  a 


export NumNegate (numNegate)


class NumAbs (a : Type) where 
 
  abs :  a →  a 


export NumAbs (abs)


class NumAdd (a : Type) where 
 
  numAdd :  a →  a →  a


export NumAdd (numAdd)


class NumMinus (a : Type) where 
 
  numMinus :  a →  a →  a


export NumMinus (numMinus)


class NumMult (a : Type) where 
 
  numMult :  a →  a →  a


export NumMult (numMult)


class NumPow (a : Type) where 
 
  numPow :  a →  Nat →  a


export NumPow (numPow)


class NumDivision (a : Type) where 
 
  numDivision :  a →  a →  a


export NumDivision (numDivision)


class NumIntegerDivision (a : Type) where 
 
  numIntegerDivision :  a →  a →  a


export NumIntegerDivision (numIntegerDivision)



class NumRemainder (a : Type) where 
 
  numRemainder :  a →  a →  a


export NumRemainder (numRemainder)


class NumSucc (a : Type) where 
 
  succ :  a →  a


export NumSucc (succ)


class NumPred (a : Type) where 
 
  pred :  a →  a


export NumPred (pred)

/- 


/-  -----------------------  -/
/-  natural                  -/
/-  -----------------------  -/

/-  unbounded size natural numbers  -/
abbrev  natural := Nat
 -/
/- 


/-  -----------------------  -/
/-  int                      -/
/-  -----------------------  -/

/-  bounded size integers with uncertain length  -/

abbrev  int := Int
 -/
/- 


/-  -----------------------  -/
/-  integer                  -/
/-  -----------------------  -/

/-  unbounded size integers  -/

abbrev  integer := Int
 -/
/- 

/-  -----------------------  -/
/-  bint                     -/
/-  -----------------------  -/

/-  TODO the bounded ints are only partially implemented, use with care.  -/

/-  32 bit integers  -/
abbrev  int32 := Int32
 -/
/-  /-  newtype wrapper â distinct from Int  -/

/-  64 bit integers  -/
abbrev  int64 := Int64
 -/
/-  /-  newtype wrapper â distinct from Int  -/


/-  -----------------------  -/
/-  rational                 -/
/-  -----------------------  -/

/-  unbounded size and precision rational numbers  -/

abbrev  rational := LemUnsupported.rational
 -/
/-  /-  ???: better type for this in HOL?  -/


/-  -----------------------  -/
/-  real                     -/
/-  -----------------------  -/

/-  real numbers  -/
/-  Note that for OCaml, this is mapped to floats with 64 bits.  -/

abbrev  real := LemUnsupported.real
 -/
/-  /-  ???: better type for this in HOL?  -/


/-  -----------------------  -/
/-  double                   -/
/-  -----------------------  -/

/-  double precision floating point (64 bits)  -/

abbrev  float64 := LemUnsupported.float64
 -/
/-  /-  ???: better type for this in HOL?  -/

abbrev  float32 := LemUnsupported.float32
 -/
/- removed value specification -/

/- 

instance   : Numeral Nat where

    fromNumeral   n  :=    n
 -/
/- removed value specification -/


instance   : Eq0 Nat where

    isEqual   :=  (fun x y => x == y)

    isInequal   n1  n2  :=  not  (n1  ==  n2)

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/




instance   : Ord0 Nat where

    compare   :=  defaultCompare

    isLess   :=  natLtb

    isLessEqual   :=  natLteb

    isGreater   :=  natGtb

    isGreaterEqual   :=  natGteb


instance   : SetType Nat where

    setElemCompare   :=  defaultCompare

/- removed value specification -/


instance   : NumAdd Nat where

    numAdd   :=  (fun x y => x + y)

/- removed value specification -/


instance   : NumMinus Nat where

    numMinus   :=  (fun x y => x - y)

/- removed value specification -/

/- 
def  natSucc  (n : Nat)  : Nat :=  n  +  1 -/
instance   : NumSucc Nat where

    succ   :=  Nat.succ

/- removed value specification -/


instance   : NumPred Nat where

    pred   :=  Nat.pred

/- removed value specification -/


instance   : NumMult Nat where

    numMult   :=  (fun x y => x * y)

/- removed value specification -/


instance   : NumIntegerDivision Nat where
 
    numIntegerDivision   :=  lemNatDiv


instance   : NumDivision Nat where
 
    numDivision   :=  lemNatDiv

/- removed value specification -/


instance   : NumRemainder Nat where
 
    numRemainder   :=  lemNatMod

/- removed value specification -/

/- 
 def  gen_pow_aux  {a : Type}   (mul  : a →  a →  a)  (a  : a)  (b  : a)  (e  : Nat)  : a := 
   match  e with  |  0 =>  a |  1 =>  mul  a  b | (  (e' + 2)) => ( let  e''  := /  e  2;                     let  a'   := (if  (mod  e  2)  =  0 then  a  else  mul  a  b);                     gen_pow_aux  mul  a'  (mul  b  b)  e'')
    -/
       
def  gen_pow  {a : Type}   (one  : a)  (mul  : a →  a →  a)  (b  : a)  (e  : Nat)   :  a :=  
  if  natLtb  e (  0) then  one  else  
  if  (e  ==   0) then  one  else  gen_pow_aux  mul  one  b  e
/- removed value specification -/


instance   : NumPow Nat where
 
    numPow   :=  natPower

/- removed value specification -/


/- removed value specification -/



instance   : OrdMaxMin Nat where
 
    max   :=  natMax

    min   :=  natMin

/- removed value specification -/

/- 

instance   : Numeral Nat where

    fromNumeral   n  :=    n
 -/
/- removed value specification -/


instance   : Eq0 Nat where

    isEqual   :=  (fun x y => x == y)

    isInequal   n1  n2  :=  not  (n1  ==  n2)

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/




instance   : Ord0 Nat where

    compare   :=  defaultCompare

    isLess   :=  natLtb

    isLessEqual   :=  natLteb

    isGreater   :=  natGtb

    isGreaterEqual   :=  natGteb


instance   : SetType Nat where

    setElemCompare   :=  defaultCompare

/- removed value specification -/


instance   : NumAdd Nat where

    numAdd   :=  (fun x y => x + y)

/- removed value specification -/


instance   : NumMinus Nat where

    numMinus   :=  (fun x y => x - y)

/- removed value specification -/

/- 
def  naturalSucc  (n : Nat)  : Nat :=  n  +  1 -/
instance   : NumSucc Nat where

    succ   :=  Nat.succ

/- removed value specification -/


instance   : NumPred Nat where

    pred   :=  Nat.pred

/- removed value specification -/


instance   : NumMult Nat where

    numMult   :=  (fun x y => x * y)

/- removed value specification -/


instance   : NumPow Nat where
 
    numPow   :=  natPower

/- removed value specification -/


instance   : NumIntegerDivision Nat where
 
    numIntegerDivision   :=  lemNatDiv


instance   : NumDivision Nat where
 
    numDivision   :=  lemNatDiv

/- removed value specification -/


instance   : NumRemainder Nat where
 
    numRemainder   :=  lemNatMod

/- removed value specification -/


/- removed value specification -/



instance   : OrdMaxMin Nat where
 
    max   :=  natMax

    min   :=  natMin

/- removed value specification -/

/- 

instance   : Numeral Int where

    fromNumeral   n  :=  ( n :  Int)
 -/
/- removed value specification -/


instance   : Eq0 Int where

    isEqual   :=  (fun x y => x == y)

    isInequal   n1  n2  :=  not  (n1  ==  n2)

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/




instance   : Ord0 Int where

    compare   :=  defaultCompare

    isLess   :=  intLtb

    isLessEqual   :=  intLteb

    isGreater   :=  intGtb

    isGreaterEqual   :=  intGteb


instance   : SetType Int where

    setElemCompare   :=  defaultCompare

/- removed value specification -/


instance   : NumNegate Int where

    numNegate   :=  (fun  i=> (Int.neg  i))

/- removed value specification -/


instance   : NumAbs Int where

    abs   :=  intAbs

/- removed value specification -/


instance   : NumAdd Int where

    numAdd   :=  (fun x y => x + y)

/- removed value specification -/


instance   : NumMinus Int where

    numMinus   :=  (fun x y => x - y)

/- removed value specification -/


instance   : NumSucc Int where

    succ   :=  (fun  n=> n  + ( 1 :  Int))

/- removed value specification -/


instance   : NumPred Int where

    pred   :=  (fun  n=> n  - ( 1 :  Int))

/- removed value specification -/


instance   : NumMult Int where

    numMult   :=  (fun x y => x * y)

/- removed value specification -/


instance   : NumPow Int where
 
    numPow   :=  (fun x y => x ^ y)

/- removed value specification -/


instance   : NumIntegerDivision Int where
 
    numIntegerDivision   :=  lemIntDiv


instance   : NumDivision Int where
 
    numDivision   :=  lemIntDiv

/- removed value specification -/


instance   : NumRemainder Int where
 
    numRemainder   :=  lemIntMod

/- removed value specification -/


/- removed value specification -/



instance   : OrdMaxMin Int where
 
    max   :=  max

    min   :=  min

/- removed value specification -/

/- 

instance   : Numeral Int32 where

    fromNumeral   n  :=  lemInt32FromNumeral  n
 -/
/- removed value specification -/



instance   : Eq0 Int32 where

    isEqual   :=  (fun x y => x == y)

    isInequal   n1  n2  :=  not  (n1  ==  n2)

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/



/- removed value specification -/




instance   : Ord0 Int32 where

    compare   :=  defaultCompare

    isLess   :=  lemInt32Ltb

    isLessEqual   :=  lemInt32Lteb

    isGreater   :=  lemInt32Gtb

    isGreaterEqual   :=  lemInt32Gteb


instance   : SetType Int32 where

    setElemCompare   :=  defaultCompare

/- removed value specification -/


instance   : NumNegate Int32 where

    numNegate   :=  Neg.neg

/- removed value specification -/

/- 
def  int32Abs  (i : Int32)  : Int32 :=  (if  <=  0  i then  i  else  ~ i) -/

instance   : NumAbs Int32 where

    abs   :=  Int32.abs

/- removed value specification -/


instance   : NumAdd Int32 where

    numAdd   :=  (fun x y => x + y)

/- removed value specification -/


instance   : NumMinus Int32 where

    numMinus   :=  (fun x y => x - y)

/- removed value specification -/



instance   : NumSucc Int32 where

    succ   :=  (fun  n=> n  + lemInt32FromNumeral  1)

/- removed value specification -/


instance   : NumPred Int32 where

    pred   :=  (fun  n=> n  - lemInt32FromNumeral  1)

/- removed value specification -/


instance   : NumMult Int32 where

    numMult   :=  (fun x y => x * y)

/- removed value specification -/


instance   : NumPow Int32 where
 
    numPow   :=  (fun x y => x ^ y)

/- removed value specification -/


instance   : NumIntegerDivision Int32 where
 
    numIntegerDivision   :=  lemInt32Div


instance   : NumDivision Int32 where
 
    numDivision   :=  lemInt32Div

/- removed value specification -/


instance   : NumRemainder Int32 where
 
    numRemainder   :=  lemInt32Mod

/- removed value specification -/


/- removed value specification -/



instance   : OrdMaxMin Int32 where
 
    max   :=  max

    min   :=  min

/- removed value specification -/

/- 

instance   : Numeral Int64 where

    fromNumeral   n  :=  lemInt64FromNumeral  n
 -/
/- removed value specification -/



instance   : Eq0 Int64 where

    isEqual   :=  (fun x y => x == y)

    isInequal   n1  n2  :=  not  (n1  ==  n2)

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/



/- removed value specification -/




instance   : Ord0 Int64 where

    compare   :=  defaultCompare

    isLess   :=  lemInt64Ltb

    isLessEqual   :=  lemInt64Lteb

    isGreater   :=  lemInt64Gtb

    isGreaterEqual   :=  lemInt64Gteb


instance   : SetType Int64 where

    setElemCompare   :=  defaultCompare

/- removed value specification -/


instance   : NumNegate Int64 where

    numNegate   :=  Neg.neg

/- removed value specification -/

/- 
def  int64Abs  (i : Int64)  : Int64 :=  (if  <=  0  i then  i  else  ~ i) -/

instance   : NumAbs Int64 where

    abs   :=  Int64.abs

/- removed value specification -/


instance   : NumAdd Int64 where

    numAdd   :=  (fun x y => x + y)

/- removed value specification -/


instance   : NumMinus Int64 where

    numMinus   :=  (fun x y => x - y)

/- removed value specification -/



instance   : NumSucc Int64 where

    succ   :=  (fun  n=> n  + lemInt64FromNumeral  1)

/- removed value specification -/


instance   : NumPred Int64 where

    pred   :=  (fun  n=> n  - lemInt64FromNumeral  1)

/- removed value specification -/


instance   : NumMult Int64 where

    numMult   :=  (fun x y => x * y)

/- removed value specification -/


instance   : NumPow Int64 where
 
    numPow   :=  (fun x y => x ^ y)

/- removed value specification -/


instance   : NumIntegerDivision Int64 where
 
    numIntegerDivision   :=  lemInt64Div


instance   : NumDivision Int64 where
 
    numDivision   :=  lemInt64Div

/- removed value specification -/


instance   : NumRemainder Int64 where
 
    numRemainder   :=  lemInt64Mod

/- removed value specification -/


/- removed value specification -/



instance   : OrdMaxMin Int64 where
 
    max   :=  max

    min   :=  min

/- removed value specification -/

/- 

instance   : Numeral Int where

    fromNumeral   n  :=  ( n :  Int)
 -/
/- removed value specification -/

/- removed value specification -/


instance   : Eq0 Int where

    isEqual   :=  (fun x y => x == y)

    isInequal   n1  n2  :=  not  (n1  ==  n2)

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/




instance   : Ord0 Int where

    compare   :=  defaultCompare

    isLess   :=  intLtb

    isLessEqual   :=  intLteb

    isGreater   :=  intGtb

    isGreaterEqual   :=  intGteb


instance   : SetType Int where

    setElemCompare   :=  defaultCompare

/- removed value specification -/


instance   : NumNegate Int where

    numNegate   :=  (fun  i=> (Int.neg  i))

/- removed value specification -/


instance   : NumAbs Int where

    abs   :=  intAbs

/- removed value specification -/


instance   : NumAdd Int where

    numAdd   :=  (fun x y => x + y)

/- removed value specification -/


instance   : NumMinus Int where

    numMinus   :=  (fun x y => x - y)

/- removed value specification -/


instance   : NumSucc Int where

    succ   :=  (fun  n=> n  + ( 1 :  Int))

/- removed value specification -/


instance   : NumPred Int where

    pred   :=  (fun  n=> n  - ( 1 :  Int))

/- removed value specification -/


instance   : NumMult Int where

    numMult   :=  (fun x y => x * y)

/- removed value specification -/


instance   : NumPow Int where
 
    numPow   :=  (fun x y => x ^ y)

/- removed value specification -/


instance   : NumIntegerDivision Int where
 
    numIntegerDivision   :=  lemIntegerDiv


instance   : NumDivision Int where
 
    numDivision   :=  lemIntegerDiv

/- removed value specification -/


instance   : NumRemainder Int where
 
    numRemainder   :=  lemIntegerMod

/- removed value specification -/


/- removed value specification -/



instance   : OrdMaxMin Int where
 
    max   :=  max

    min   :=  min

/- removed value specification -/

/- 

instance   : Numeral LemUnsupported.rational where

    fromNumeral   n  :=  LemUnsupported.rationalFromNumeral  n
 -/
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/


instance   : Eq0 LemUnsupported.rational where

    isEqual   :=  (fun x y => x == y)

    isInequal   n1  n2  :=  not  (n1  ==  n2)

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/




instance   : Ord0 LemUnsupported.rational where

    compare   :=  defaultCompare

    isLess   :=  unsupportedRationalLess

    isLessEqual   :=  unsupportedRationalLessEq

    isGreater   :=  unsupportedRationalGreater

    isGreaterEqual   :=  unsupportedRationalGreaterEq


instance   : SetType LemUnsupported.rational where

    setElemCompare   :=  defaultCompare

/- removed value specification -/


instance   : NumAdd LemUnsupported.rational where

    numAdd   :=  (fun x y => x + y)

/- removed value specification -/


instance   : NumMinus LemUnsupported.rational where

    numMinus   :=  (fun x y => x - y)

/- removed value specification -/



instance   : NumNegate LemUnsupported.rational where

    numNegate   :=  (fun  n=> LemUnsupported.rationalFromNumeral  0  -  n)

/- removed value specification -/



instance   : NumAbs LemUnsupported.rational where

    abs   :=  (fun  n=> (if  unsupportedRationalGreater  n (LemUnsupported.rationalFromNumeral  0) then  n  else LemUnsupported.rationalFromNumeral  0  -  n))

/- removed value specification -/


instance   : NumSucc LemUnsupported.rational where

    succ   :=  (fun  n=> n  + LemUnsupported.rationalFromNumeral  1)

/- removed value specification -/


instance   : NumPred LemUnsupported.rational where

    pred   :=  (fun  n=> n  - LemUnsupported.rationalFromNumeral  1)

/- removed value specification -/


instance   : NumMult LemUnsupported.rational where

    numMult   :=  (fun x y => x * y)

/- removed value specification -/


instance   : NumDivision LemUnsupported.rational where

    numDivision   :=  (fun x y => x / y)

/- removed value specification -/

/- 
def  rationalFromFrac  (n : Int) (d : Int)  : LemUnsupported.rational :=  (LemUnsupported.rationalFromInt  n)  /  (LemUnsupported.rationalFromInt  d) -/
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- 
 partial def  rationalPowInteger  (b : LemUnsupported.rational) (e : Int)  : LemUnsupported.rational := 
  if  e  =  0 then  1  else 
  if  >  e  0 then  b  ^  (e  -  1)  *  b  else 
  b  ^  (e  +  1)  /  b -/
/- removed value specification -/

/- 
def  rationalPowNat  (r : LemUnsupported.rational) (e : Nat)  : LemUnsupported.rational :=  r  ^  (Int.ofNat  e) -/

instance   : NumPow LemUnsupported.rational where

    numPow   :=  (fun x y => x ^ y)

/- removed value specification -/


/- removed value specification -/



instance   : OrdMaxMin LemUnsupported.rational where

    max   :=  max

    min   :=  min

/- removed value specification -/

/- 

instance   : Numeral LemUnsupported.real where

    fromNumeral   n  :=  LemUnsupported.realFromNumeral  n
 -/
/- removed value specification -/

/- removed value specification -/


instance   : Eq0 LemUnsupported.real where

    isEqual   :=  (fun x y => x == y)

    isInequal   n1  n2  :=  not  (n1  ==  n2)

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/




instance   : Ord0 LemUnsupported.real where

    compare   :=  defaultCompare

    isLess   :=  unsupportedRealLess

    isLessEqual   :=  unsupportedRealLessEq

    isGreater   :=  unsupportedRealGreater

    isGreaterEqual   :=  unsupportedRealGreaterEq


instance   : SetType LemUnsupported.real where

    setElemCompare   :=  defaultCompare

/- removed value specification -/


instance   : NumAdd LemUnsupported.real where

    numAdd   :=  (fun x y => x + y)

/- removed value specification -/


instance   : NumMinus LemUnsupported.real where

    numMinus   :=  (fun x y => x - y)

/- removed value specification -/



instance   : NumNegate LemUnsupported.real where

    numNegate   :=  Neg.neg

/- removed value specification -/



instance   : NumAbs LemUnsupported.real where

    abs   :=  unsupportedRealAbs

/- removed value specification -/


instance   : NumSucc LemUnsupported.real where

    succ   :=  (fun  n=> n  + LemUnsupported.realFromNumeral  1)

/- removed value specification -/


instance   : NumPred LemUnsupported.real where

    pred   :=  (fun  n=> n  - LemUnsupported.realFromNumeral  1)

/- removed value specification -/


instance   : NumMult LemUnsupported.real where

    numMult   :=  (fun x y => x * y)

/- removed value specification -/


instance   : NumDivision LemUnsupported.real where

    numDivision   :=  (fun x y => x / y)

/- removed value specification -/

/- 
def  realFromFrac  (n : Int) (d : Int)  : LemUnsupported.real :=  (LemUnsupported.realFromInt  n)  /  (LemUnsupported.realFromInt  d) -/
/- removed value specification -/

/- 
 partial def  realPowInteger  (b : LemUnsupported.real) (e : Int)  : LemUnsupported.real := 
  if  e  =  0 then  1  else 
  if  >  e  0 then  b  ^  (e  -  1)  *  b  else 
  b  ^  (e  +  1)  /  b -/
/- removed value specification -/

/- 
def  realPowNat  (r : LemUnsupported.real) (e : Nat)  : LemUnsupported.real :=  r  ^  (Int.ofNat  e) -/

instance   : NumPow LemUnsupported.real where

    numPow   :=  (fun x y => x ^ y)

/- removed value specification -/

/- removed value specification -/


/- removed value specification -/



instance   : OrdMaxMin LemUnsupported.real where

    max   :=  max

    min   :=  min

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- 
def  integerSqrt  (i : Int)  : Int :=  realFloor  (realSqrt  (LemUnsupported.realFromInt  i)) -/
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- 
def  int32FromInteger  (i : Int)  : Int32 :=  (
  let  abs_int32  := lemInt32OfNaturalExact  (Int.natAbs  i); 
  if  (<  i  0) then  (~  abs_int32)  else  abs_int32 
) -/
/- removed value specification -/

/- 
def  int32FromInt  (i : Int)  : Int32 :=  lemInt32OfIntegerExact  (  i) -/
/- removed value specification -/

/- 
def  int32FromInt64  (i : Int64)  : Int32 :=  lemInt32OfIntegerExact  (lemInt64ToInt  i) -/
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- 
def  int64FromInteger  (i : Int)  : Int64 :=  (
  let  abs_int64  := lemInt64OfNaturalExact  (Int.natAbs  i); 
  if  (<  i  0) then  (~  abs_int64)  else  abs_int64 
) -/
/- removed value specification -/

/- 
def  int64FromInt  (i : Int)  : Int64 :=  lemInt64OfIntegerExact  (  i) -/
/- removed value specification -/

/- 
def  int64FromInt32  (i : Int32)  : Int64 :=  lemInt64OfIntegerExact  (lemInt32ToInt  i) -/
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/





/- removed value specification -/

/- removed value specification -/

/- removed value specification -/





/- removed value specification -/

/- removed value specification -/

/- removed value specification -/





end Lem_Num

