/- Generated by Lem from relation.lem. -/

import LemLib

import LemLib.Bool
import LemLib.Basic_classes
import LemLib.Tuple
import LemLib.Set
import LemLib.Num

namespace Lem_Relation
 /- **************************************************************************** -/
/- A library for binary relations                                             -/
/- **************************************************************************** -/
/- ========================================================================== -/
/- Header                                                                     -/
/- ========================================================================== -/

open Lem_Bool
open Lem_Basic_classes
open Lem_Tuple
open Lem_Set
open Lem_Num

/- ========================================================================== -/
/- The type of relations                                                      -/
/- ========================================================================== -/

abbrev rel_pred (a : Type) (b : Type) := a → b → Bool

abbrev rel_set (a : Type) (b : Type) := Pset (a × b)

/- Binary relations are usually represented as either
   sets of pairs (rel_set) or as curried functions (rel_pred). 
   
   The choice depends on taste and the backend. Lem should not take a 
   decision, but supports both representations. There is an abstract type
   pred, which can be converted to both representations. The representation
   of pred itself then depends on the backend. However, for the time beeing,
   let's implement relations as sets to get them working more quickly. -/

abbrev rel (a : Type) (b : Type) := rel_set a b

def relEq {a b : Type} [SetType a] [SetType b] (r1 : Pset (a × b)) (r2 : Pset (a × b)) : Bool := ((setEqualBy (pairCompare (@setElemCompare a _) (@setElemCompare b _)) r1 r2))

def relToPred {a b : Type} [SetType a] [SetType b] [Eq0 a] [Eq0 b] (r : Pset (a × b)) : a → b → Bool := (fun (x : a) (y : b) => (setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare b _)) (x, y) r))
def relFromPred {a b : Type} [SetType a] [SetType b] [Eq0 a] [Eq0 b] (xs : Pset a) (ys : Pset b) (p : a → b → Bool) : Pset (a × b) := setFilterBy setElemCompare (fun (p0 : (a × b)) => match p0 with | (x, y) => p x y) ((setCrossBy (pairCompare (@setElemCompare a _) (@setElemCompare b _)) xs ys))
/- ========================================================================== -/
/- Basic Operations                                                           -/
/- ========================================================================== -/
/- ----------------------- -/
/- membership test         -/
/- ----------------------- -/

/- ----------------------- -/
/- empty relation          -/
/- ----------------------- -/

/- ----------------------- -/
/- Insertion               -/
/- ----------------------- -/

/- ----------------------- -/
/- Identity relation       -/
/- ----------------------- -/

def relIdOn {a : Type} [SetType a] [Eq0 a] (s : Pset a) : Pset (a × a) := relFromPred s s (fun x y => x == y)
/- ----------------------- -/
/- relation union          -/
/- ----------------------- -/

/- ----------------------- -/
/- relation intersection   -/
/- ----------------------- -/

/- ----------------------- -/
/- Relation Composition    -/
/- ----------------------- -/

def relComp {a b c : Type} [SetType a] [SetType b] [SetType c] [Eq0 a] [Eq0 b] (r1 : Pset (a × b)) (r2 : Pset (b × c)) : Pset (a × c) := let x2 := setEmpty; setFold (fun (p : (a × b)) (x2 : Pset (a × c)) => match p, x2 with | (e1, e2), x2 => setFold (fun (p : (b × c)) (x2 : Pset (a × c)) => match p, x2 with | (e2', e3), x2 => (lem_if e2 == e2' then setAddBy setElemCompare (e1, e3) x2 else x2)) r2 x2) r1 x2
/- ----------------------- -/
/- restrict                -/
/- ----------------------- -/

def relRestrict {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) (s : Pset a) : Pset (a × a) := (let x2 := setEmpty; setFold (fun (a1 : a) (x2 : Pset (a × a)) => setFold (fun (b : a) (x2 : Pset (a × a)) => lem_if (setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (a1, b) r) then setAddBy setElemCompare (a1, b) x2 else x2) s x2) s x2)
/- ----------------------- -/
/- Converse                -/
/- ----------------------- -/

def relConverse {a b : Type} [SetType a] [SetType b] (r : Pset (a × b)) : Pset (b × a) := ((setMapBy (pairCompare (@setElemCompare b _) (@setElemCompare a _)) swap r))
/- ----------------------- -/
/- domain                  -/
/- ----------------------- -/

def relDomain {a b : Type} [SetType a] [SetType b] (r : Pset (a × b)) : Pset a := (setMapBy (@setElemCompare a _) (fun (x : (a × b)) => Prod.fst x) r)
/- ----------------------- -/
/- range                   -/
/- ----------------------- -/

def relRange {a b : Type} [SetType a] [SetType b] (r : Pset (a × b)) : Pset b := (setMapBy (@setElemCompare b _) (fun (x : (a × b)) => Prod.snd x) r)
/- ----------------------- -/
/- field / definedOn       -/
/-                         -/
/- avoid the keyword field -/
/- ----------------------- -/

/- ----------------------- -/
/- relOver                 -/
/-                         -/
/- avoid the keyword field -/
/- ----------------------- -/

def relOver {a : Type} [SetType a] (r : Pset (a × a)) (s : Pset a) : Bool := ((setSubsetBy (@setElemCompare a _) (((setUnionBy (@setElemCompare a _) (relDomain r) (relRange r)))) s))
/- ----------------------- -/
/- apply a relation        -/
/- ----------------------- -/
/- Given a relation r and a set s, relApply r s applies s to r, i.e.
   it returns the set of all value reachable via r from a value in s.
   This operation can be seen as a generalisation of function application. -/

def relApply {a b : Type} [SetType a] [SetType b] [Eq0 a] (r : Pset (a × b)) (s : Pset a) : Pset b := let x2 := setEmpty; setFold (fun (p : (a × b)) (x2 : Pset b) => match p, x2 with | (x, y), x2 => (lem_if (setMemberBy (@setElemCompare a _) x s) then setAddBy setElemCompare y x2 else x2)) r x2
/- ========================================================================== -/
/- Properties                                                                 -/
/- ========================================================================== -/
/- ----------------------- -/
/- subrel                  -/
/- ----------------------- -/

/- ----------------------- -/
/- reflexivity             -/
/- ----------------------- -/

def isReflexiveOn {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) (s : Pset a) : Bool := (setForAll (fun (e : a) => (setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (e, e) r)) s)
/- ----------------------- -/
/- irreflexivity           -/
/- ----------------------- -/

def isIrreflexiveOn {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) (s : Pset a) : Bool := (setForAll (fun (e : a) => not ((setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (e, e) r))) s)
def isIrreflexive {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) : Bool := (setForAll (fun (p : (a × a)) => match p with | (e1, e2) => not (e1 == e2)) r)
/- ----------------------- -/
/- symmetry                -/
/- ----------------------- -/

def isSymmetricOn {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) (s : Pset a) : Bool := (setForAll (fun (e1 : a) => setForAll (fun (e2 : a) => ((not ((setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (e1, e2) r))) || ((setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (e2, e1) r)))) s) s)
def isSymmetric {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) : Bool := (setForAll (fun (p : (a × a)) => match p with | (e1, e2) => (setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (e2, e1) r)) r)
/- ----------------------- -/
/- antisymmetry            -/
/- ----------------------- -/

def isAntisymmetricOn {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) (s : Pset a) : Bool := (setForAll (fun (e1 : a) => setForAll (fun (e2 : a) => ((not ((setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (e1, e2) r))) || ((not ((setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (e2, e1) r))) || (e1 == e2)))) s) s)
def isAntisymmetric {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) : Bool := (setForAll (fun (p : (a × a)) => match p with | (e1, e2) => ((not ((setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (e2, e1) r))) || (e1 == e2))) r)
/- ----------------------- -/
/- transitivity            -/
/- ----------------------- -/

def isTransitiveOn {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) (s : Pset a) : Bool := (setForAll (fun (e1 : a) => setForAll (fun (e2 : a) => setForAll (fun (e3 : a) => ((not ((setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (e1, e2) r))) || ((not ((setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (e2, e3) r))) || ((setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (e1, e3) r))))) s) s) s)
def isTransitive {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) : Bool := (setForAll (fun (p : (a × a)) => match p with | (e1, e2) => setForAll (fun (e3 : a) => (setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (e1, e3) r)) (relApply r (setFromListBy setElemCompare [e2]))) r)
/- ----------------------- -/
/- total                   -/
/- ----------------------- -/

def isTotalOn {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) (s : Pset a) : Bool := (setForAll (fun (e1 : a) => setForAll (fun (e2 : a) => ((setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (e1, e2) r)) || ((setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (e2, e1) r))) s) s)
def isTrichotomousOn {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) (s : Pset a) : Bool := (setForAll (fun (e1 : a) => setForAll (fun (e2 : a) => ((setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (e1, e2) r)) || ((e1 == e2) || ((setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (e2, e1) r)))) s) s)
/- ----------------------- -/
/- is_single_valued        -/
/- ----------------------- -/

def isSingleValued {a b : Type} [SetType a] [SetType b] [Eq0 a] [Eq0 b] (r : Pset (a × b)) : Bool := (setForAll (fun (p : (a × b)) => match p with | (e1, e2a) => setForAll (fun (e2b : b) => e2a == e2b) (relApply r (setFromListBy setElemCompare [e1]))) r)
/- ----------------------- -/
/- equivalence relation    -/
/- ----------------------- -/

def isEquivalenceOn {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) (s : Pset a) : Bool := isReflexiveOn r s && (isSymmetricOn r s && isTransitiveOn r s)
/- ----------------------- -/
/- well founded            -/
/- ----------------------- -/

/- ========================================================================== -/
/- Orders                                                                     -/
/- ========================================================================== -/
/- ----------------------- -/
/- pre- or quasiorders     -/
/- ----------------------- -/

def isPreorderOn {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) (s : Pset a) : Bool := isReflexiveOn r s && isTransitiveOn r s
/- ----------------------- -/
/- partial orders          -/
/- ----------------------- -/

def isPartialOrderOn {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) (s : Pset a) : Bool := isReflexiveOn r s && (isTransitiveOn r s && isAntisymmetricOn r s)
def isStrictPartialOrderOn {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) (s : Pset a) : Bool := isIrreflexiveOn r s && isTransitiveOn r s
def isStrictPartialOrder {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) : Bool := isIrreflexive r && isTransitive r
/- ----------------------- -/
/- total / linear orders   -/
/- ----------------------- -/

def isTotalOrderOn {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) (s : Pset a) : Bool := isPartialOrderOn r s && isTotalOn r s
def isStrictTotalOrderOn {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) (s : Pset a) : Bool := isStrictPartialOrderOn r s && isTrichotomousOn r s
/- ========================================================================== -/
/- closures                                                                   -/
/- ========================================================================== -/
/- ----------------------- -/
/- transitive closure      -/
/- ----------------------- -/

/- lean: no rep for transitiveClosureByEq — the OCaml target has none either
   (unbound for both targets; parity-fix slice 2026-09-03) -/
/- arc-14 re-mark R1 (the be:G4 class): the lean transitiveClosure inline
   routes through the COMPARATOR form, mirroring the ocaml inline — the
   ByEq route joined/deduped by lem (=) (BEq), which with a BEq finer
   than the set comparator diverges from the comparator-keyed Pset.tc. -/

/- ----------------------- -/
/- transitive closure step -/
/- ----------------------- -/

def transitiveClosureAdd {a : Type} [SetType a] [Eq0 a] (x : a) (y : a) (r : Pset (a × a)) : Pset (a × a) :=
  (((setUnionBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (((setAddBy setElemCompare (x,y) r))) ((((setUnionBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) ((let x2 := setEmpty; setFold (fun (z : a) (x2 : Pset (a × a)) => lem_if (setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (y, z) r) then setAddBy setElemCompare (x, z) x2 else x2) (relRange r) x2)) ((let x2 := setEmpty; setFold (fun (z : a) (x2 : Pset (a × a)) => lem_if (setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (z, x) r) then setAddBy setElemCompare (z, y) x2 else x2) (relDomain r) x2)))))))))
/- ========================================================================== -/
/- reflexive closure                                                          -/
/- ========================================================================== -/

def reflexiveTransitiveClosureOn {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) (s : Pset a) : Pset (a × a) := (set_tcByCmp (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (((setUnionBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) r ((relIdOn s))))))
/- ========================================================================== -/
/- inverse of closures                                                        -/
/- ========================================================================== -/
/- ----------------------- -/
/- without transitve edges -/
/- ----------------------- -/

def withoutTransitiveEdges {a : Type} [SetType a] [Eq0 a] (r : Pset (a × a)) : Pset (a × a) :=
  let tc := (set_tcByCmp (pairCompare (@setElemCompare a _) (@setElemCompare a _)) r);
  let x2 := setEmpty; setFold (fun (p : (a × a)) (x2 : Pset (a × a)) => match p, x2 with | (a1, c), x2 => (lem_if setForAll (fun (b : a) => ((not ((a1 != b) && (b != c))) || not ((setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (a1, b) tc) && (setMemberBy (pairCompare (@setElemCompare a _) (@setElemCompare a _)) (b, c) tc)))) (relRange r) then setAddBy setElemCompare (a1, c) x2 else x2)) r x2
end Lem_Relation
