/- Generated by Lem from set.lem. -/

import LemLib

import LemLib.Bool
import LemLib.Basic_classes
import LemLib.Maybe
import LemLib.Function
import LemLib.Num
import LemLib.List
import LemLib.Set_helpers

namespace Lem_Set
/- **************************************************************************** -/
/-  A library for sets                                                          -/
/-                                                                              -/
/-  It mainly follows the Haskell Set-library                                   -/
/- **************************************************************************** -/

/-  Sets in Lem are a bit tricky. On the one hand, we want efficiently executable sets.
   OCaml and Haskell both represent sets by some kind of balancing trees. This means
   that sets are finite and an order on the element type is required. 
   Such sets are constructed by simple, executable operations like inserting or
   deleting elements, union, intersection, filtering etc.

   On the other hand, we want to use sets for specifications. This leads often
   infinite sets, which are specificied in complicated, perhaps even undecidable
   ways.

   The set library in this file, chooses the first approach. It describes 
   *finite* sets with an underlying order. Infinite sets should in the medium
   run be represented by a separate type. Since this would require some significant
   changes to Lem, for the moment also infinite sets are represented using this
   class. However, a run-time exception might occour when using these sets. 
   This problem needs adressing in the future.  -/
   

/-  ==========================================================================  -/
/-  Header                                                                      -/
/-  ==========================================================================  -/

open Lem_Bool
open Lem_Basic_classes
open Lem_Maybe
open Lem_Function
open Lem_Num
open Lem_List
open Lem_Set_helpers


/-  DPM: sets currently implemented as lists due to mismatch between Coq type
 * class hierarchy and the hierarchy implemented in Lem.
  -/



/- removed value specification -/

/- removed value specification -/





instance (a : Type) [SetType a] : Eq0 (Pset  a) where

    isEqual   :=  (setEqualBy  (@setElemCompare (a) _))

    isInequal   s1  s2  :=  not  ((setEqualBy  (@setElemCompare (a) _)  s1  s2))

/- removed value specification -/

/- removed value specification -/


/- removed value specification -/
 

/- removed value specification -/


/- removed value specification -/

/- removed value specification -/



/- removed value specification -/
 

/- removed value specification -/
 /-  before is_empty  -/

/- removed value specification -/

/- removed value specification -/




/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/



/- removed value specification -/

/- removed value specification -/

/-  
def  filter  {a : Type} [SetType a]  (P : a → Bool) (s : Pset a)  : Pset a := (sorry /- Lean backend: set comprehension binding not supported -/) -/
/- removed value specification -/

def  partition0  {a : Type} [SetType a]  (P : a → Bool) (s : Pset a)  : (Pset a ×Pset a) :=  (setFilterBy  setElemCompare  P  s, setFilterBy  setElemCompare  (fun (e : a) =>  not  (P  e))  s)
/- removed value specification -/

def  split  {a : Type} [SetType a] [Ord0 a]  (p : a) (s : Pset a)  : (Pset a ×Pset a) :=  (setFilterBy  setElemCompare  (isGreater  p)  s, setFilterBy  setElemCompare  (isLess  p)  s)
/- removed value specification -/

def  splitMember  {a : Type} [SetType a] [Ord0 a]  (p : a) (s : Pset a)  : (Pset a ×Bool ×Pset a) :=  (setFilterBy  setElemCompare  (isLess  p)  s, (setMemberBy  (@setElemCompare (a) _)  p  s), setFilterBy  setElemCompare  (isGreater  p)  s)
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/







/- removed value specification -/

/- removed value specification -/




/- removed value specification -/

/- removed value specification -/

/- 

def  bigunion  {a : Type} [SetType a]  (bs : Pset (Pset a))  : Pset a := (sorry /- Lean backend: set comprehension binding not supported -/) -/
/- removed value specification -/

def  bigintersection  {a : Type} [SetType a]  (bs : Pset (Pset a))  : Pset a :=  let  x2   := (setEmpty);  setFold  (fun (x : a) (x2 : Pset a) =>  if  setForAll  (fun (s : Pset a) =>  (setMemberBy  (@setElemCompare (a) _)  x  s))  bs then setAddBy  setElemCompare  x  x2  else  x2)  ((setBigunionBy  (@setElemCompare (a) _)  bs))  x2
/- removed value specification -/

/- removed value specification -/





/- removed value specification -/

/- removed value specification -/




/- removed value specification -/

/-  /-  before image  -/
def  map  {a : Type} {b : Type} [SetType a] [SetType b]  (f : a → b) (s : Pset a)  : Pset b := (sorry /- Lean backend: set comprehension binding not supported -/) -/
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/




/- removed value specification -/

def  setMapMaybe  {a : Type} {b : Type} [SetType a] [SetType b]  (f : a → Option b) (s : Pset a)  : Pset b :=  
  (setBigunionMapBy  (@setElemCompare (b) _)  (fun (x : a) =>  match  f  x with  |  some  y =>  setSingleton  y |  none =>  setEmpty
                        ) 
              s)
/- removed value specification -/

def  removeMaybe  {a : Type} [SetType a]  (s : Pset (Option a))  : Pset a :=  setMapMaybe  (fun (x : Option a) =>  x)  s
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/
 



/- removed value specification -/

/- removed value specification -/

/- 

def  sigma  {a : Type} {b : Type} [SetType a] [SetType b]  (sa : Pset a) (sb : a → Pset b)  : Pset ((a ×b)) := (sorry /- Lean backend: set comprehension binding not supported -/) -/
/- removed value specification -/

/- removed value specification -/

/- 

def  cross  {a : Type} {b : Type} [SetType a] [SetType b]  (s1 : Pset a) (s2 : Pset b)  : Pset ((a ×b)) := (sorry /- Lean backend: set comprehension binding not supported -/) -/
/- removed value specification -/



/- removed value specification -/

/- 
 partial def  leastFixedPoint  {a : Type} [SetType a]  (bound : Nat) (f : Pset a → Pset a) (x : Pset a)  : Pset a := 
  match  bound with  |  0 =>  x | (bound' + 1) => ( let  fx   := f  x;                    if  subset  fx  x then  x                    else  lemLeastFixedPoint  setElemCompare  bound'  f  (union  fx  x))
   -/
end Lem_Set
 
