/- Generated by Lem from set.lem. -/

import LemLib

import LemLib.Bool
import LemLib.Basic_classes
import LemLib.Maybe
import LemLib.Function
import LemLib.Num
import LemLib.List
import LemLib.Set_helpers

namespace Lem_Set
/- **************************************************************************** -/
/- A library for sets                                                         -/
/-                                                                            -/
/- It mainly follows the Haskell Set-library                                  -/
/- **************************************************************************** -/

/- Sets in Lem are a bit tricky. On the one hand, we want efficiently executable sets.
   OCaml and Haskell both represent sets by some kind of balancing trees. This means
   that sets are finite and an order on the element type is required. 
   Such sets are constructed by simple, executable operations like inserting or
   deleting elements, union, intersection, filtering etc.

   On the other hand, we want to use sets for specifications. This leads often
   infinite sets, which are specificied in complicated, perhaps even undecidable
   ways.

   The set library in this file, chooses the first approach. It describes 
   *finite* sets with an underlying order. Infinite sets should in the medium
   run be represented by a separate type. Since this would require some significant
   changes to Lem, for the moment also infinite sets are represented using this
   class. However, a run-time exception might occour when using these sets. 
   This problem needs adressing in the future. -/

/- ========================================================================== -/
/- Header                                                                     -/
/- ========================================================================== -/

open Lem_Bool
open Lem_Basic_classes
open Lem_Maybe
open Lem_Function
open Lem_Num
open Lem_List
open Lem_Set_helpers

/- DPM: sets currently implemented as lists due to mismatch between Coq type
 * class hierarchy and the hierarchy implemented in Lem.
 -/

/- Type of sets and set comprehensions are hard-coded -/

/- ----------------------- -/
/- Equality check          -/
/- ----------------------- -/

instance (a : Type) [SetType a] : Eq0 (Pset  a) where

    isEqual   :=  (setEqualBy  (@setElemCompare (a) _))

    isInequal   s1  s2  :=  not  ((setEqualBy  (@setElemCompare (a) _)  s1  s2))

/- ----------------------- -/
/- Empty set               -/
/- ----------------------- -/

/- ----------------------- -/
/- any / all               -/
/- ----------------------- -/

/- ----------------------- -/
/- (IN)                    -/
/- ----------------------- -/

/- ----------------------- -/
/- not (IN)                -/
/- ----------------------- -/

/- ----------------------- -/
/- Emptyness check         -/
/- ----------------------- -/
 /- before is_empty -/

/- ------------------------ -/
/- singleton                -/
/- ------------------------ -/

/- ----------------------- -/
/- size                    -/
/- ----------------------- -/

/- ---------------------------- -/
/- setting up pattern matching -/
/- --------------------------- -/

/- please provide target bindings, since choose is defined only in extra 
   and not the right thing to use here anyhow. 

let set_case s c_empty c_sing c_else =
  if (null s) then c_empty else
  if (size s = 1) then c_sing (choose s)
  else c_else
-/

/- ------------------------ -/
/- union                    -/
/- ------------------------ -/

/- ----------------------- -/
/- insert                  -/
/- ----------------------- -/
 /- before add -/
/- arc-14 S2 B3 (be:G4): comparator-keyed insert â dedupe by the SetType
   comparator (OCaml Pset.add parity), never by BEq. The args form
   splices the setElemCompare dictionary method at each call site (the
   leastFixedPoint precedent below); insert's lem type carries
   SetType 'a, so the instance always resolves. -/

/- ----------------------- -/
/- filter                  -/
/- ----------------------- -/

/- lem: replaced by its target representation:  
def  filter  {a : Type} [SetType a]  (P : a → Bool) (s : Pset a)  : Pset a := (sorry /- Lean backend: set comprehension binding not supported -/) -/
/- ----------------------- -/
/- partition               -/
/- ----------------------- -/

def  partition0  {a : Type} [SetType a]  (P : a → Bool) (s : Pset a)  : (Pset a ×Pset a) :=  (setFilterBy  setElemCompare  P  s, setFilterBy  setElemCompare  (fun (e : a) =>  not  (P  e))  s)
/- ----------------------- -/
/- split                   -/
/- ----------------------- -/

def  split  {a : Type} [SetType a] [Ord0 a]  (p : a) (s : Pset a)  : (Pset a ×Pset a) :=  (setFilterBy  setElemCompare  (isGreater  p)  s, setFilterBy  setElemCompare  (isLess  p)  s)
def  splitMember  {a : Type} [SetType a] [Ord0 a]  (p : a) (s : Pset a)  : (Pset a ×Bool ×Pset a) :=  (setFilterBy  setElemCompare  (isLess  p)  s, (setMemberBy  (@setElemCompare (a) _)  p  s), setFilterBy  setElemCompare  (isGreater  p)  s)
/- ------------------------ -/
/- subset and proper subset -/
/- ------------------------ -/

/- ------------------------ -/
/- delete                   -/
/- ------------------------ -/

/- ------------------------ -/
/- bigunion                 -/
/- ------------------------ -/

/- lem: replaced by its target representation: 

def  bigunion  {a : Type} [SetType a]  (bs : Pset (Pset a))  : Pset a := (sorry /- Lean backend: set comprehension binding not supported -/) -/
/- ------------------------ -/
/- big intersection         -/
/- ------------------------ -/
/- Shaked's addition, for which he is now forever responsible as a de facto
 * Lem maintainer...
 -/

def  bigintersection  {a : Type} [SetType a]  (bs : Pset (Pset a))  : Pset a :=  let  x2   := (setEmpty);  setFold  (fun (x : a) (x2 : Pset a) =>  lem_if  setForAll  (fun (s : Pset a) =>  (setMemberBy  (@setElemCompare (a) _)  x  s))  bs then setAddBy  setElemCompare  x  x2  else  x2)  ((setBigunionBy  (@setElemCompare (a) _)  bs))  x2
/- ------------------------ -/
/- difference               -/
/- ------------------------ -/

/- ------------------------ -/
/- intersection             -/
/- ------------------------ -/

/- ------------------------ -/
/- map                      -/
/- ------------------------ -/

/- lem: replaced by its target representation:  /- before image -/
def  map  {a : Type} {b : Type} [SetType a] [SetType b]  (f : a → b) (s : Pset a)  : Pset b := (sorry /- Lean backend: set comprehension binding not supported -/) -/
/- ------------------------ -/
/- bigunionMap              -/
/- ------------------------ -/
/- In order to avoid providing an comparison function for sets of sets,
   it might be better to combine bigunion and map sometimes into a single operation. -/

/- ------------------------ -/
/- mapMaybe and fromMaybe   -/
/- ------------------------ -/
/- If the mapping function returns Just x, x is added to the result
   set. If it returns Nothing, no element is added. -/

def  setMapMaybe  {a : Type} {b : Type} [SetType a] [SetType b]  (f : a → Option b) (s : Pset a)  : Pset b :=
  (setBigunionMapBy  (@setElemCompare (b) _)  (fun (x : a) =>  match  f  x with  |  some  y =>  setSingleton  y |  none =>  setEmpty
                        )
              s)
/- The name mapMaybe is already being used in the list.lem -/

def  removeMaybe  {a : Type} [SetType a]  (s : Pset (Option a))  : Pset a :=  setMapMaybe  (fun (x : Option a) =>  x)  s
/- ------------------------ -/
/- min and max              -/
/- ------------------------ -/

/- Informal, since THE is not supported by all backends
val findMinBy : forall 'a.  ('a -> 'a -> bool) -> ('a -> 'a -> bool) -> set 'a -> maybe 'a 
let findMinBy le eq s = THE (fun e -> ((memberBy eq e s) && (forall (e2 IN s). le e e2)))

let inline findMin = findMinBy (<=) (=)
let inline findMax = findMinBy (>=) (=)
-/

/- XXX: move into Lem libraries... -/

/- ------------------------ -/
/- fromList                 -/
/- ------------------------ -/
 /- before from_list -/

/- ------------------------ -/
/- Sigma                    -/
/- ------------------------ -/

/- lem: replaced by its target representation: 

def  sigma  {a : Type} {b : Type} [SetType a] [SetType b]  (sa : Pset a) (sb : a → Pset b)  : Pset ((a ×b)) := (sorry /- Lean backend: set comprehension binding not supported -/) -/
/- ------------------------ -/
/- cross product            -/
/- ------------------------ -/

/- lem: replaced by its target representation: 

def  cross  {a : Type} {b : Type} [SetType a] [SetType b]  (s1 : Pset a) (s2 : Pset b)  : Pset ((a ×b)) := (sorry /- Lean backend: set comprehension binding not supported -/) -/
/- ------------------------ -/
/- finite                   -/
/- ------------------------ -/

/- ---------------------------- -/
/- fixed point                 -/
/- --------------------------- -/

/- lem: replaced by its target representation: 
 partial def  leastFixedPoint  {a : Type} [SetType a]  (bound : Nat) (f : Pset a → Pset a) (x : Pset a)  : Pset a := 
  match  bound with  |  0 =>  x | (bound' + 1) => ( let  fx   := f  x;                    lem_if  subset  fx  x then  x                    else  lemLeastFixedPoint  setElemCompare  bound'  f  (union  fx  x))
   -/
end Lem_Set
