/- Generated by Lem from set_extra.lem. -/

import LemLib

import LemLib.Bool
import LemLib.Basic_classes
import LemLib.Maybe
import LemLib.Function
import LemLib.Num
import LemLib.List
import LemLib.Sorting
import LemLib.Set

namespace Lem_Set_extra
/- **************************************************************************** -/
/- A library for sets                                                         -/
/-                                                                            -/
/- It mainly follows the Haskell Set-library                                  -/
/- **************************************************************************** -/

/- ========================================================================== -/
/- Header                                                                     -/
/- ========================================================================== -/

open Lem_Bool
open Lem_Basic_classes
open Lem_Maybe
open Lem_Function
open Lem_Num
open Lem_List
open Lem_Sorting
open Lem_Set

/- ---------------------------- -/
/- set choose (be careful !)   -/
/- --------------------------- -/

/- ------------------------ -/
/- chooseAndSplit           -/
/- ------------------------ -/
/- The idea here is to provide a simple primitive that Lem code can use
 * to perform its own custom searches within the set -- likely using a
 * search criterion related to the element ordering, but not necessarily).
 * For example, sometimes we don't necessarily want to search for a specific
 * element, but want to search for elements greater than or less than some other.
 * Someties we'd like to use "split" but don't know a good value to "split" at.
 * This function lets the set implementation decide that value.
 *
 * The contract of chooseAndSplit is simply to select an element nondeterministically
 * and return that element, together with the subsets of elements less than and
 * greater than it. In this way, we can recursively traverse the set with any
 * search criterion, and we avoid baking in the tree representation (although that
 * is the obvious choice).
 -/

/- ---------------------------- -/
/- universal set               -/
/- --------------------------- -/

/- ---------------------------- -/
/- toList                      -/
/- --------------------------- -/

/- ---------------------------- -/
/- toOrderedList               -/
/- --------------------------- -/
/- "toOrderedList" returns a sorted list. Therefore the result is (given a suitable order) deterministic.
   Therefore, it is much preferred to "toList". However, it still is only defined for finite sets. So, please
   use carefully and consider using set-operations instead of translating sets to lists, performing list manipulations
   and then transforming back to sets. -/

/- ----------------------- -/
/- compare                 -/
/- ----------------------- -/

def setCompare {a : Type} [SetType a] [Ord0 a] : Pset a → Pset a → LemOrdering := setCompareBy Ord0.compare

instance (a : Type) [SetType a] : SetType (Pset a) where

    setElemCompare := setCompareBy (@setElemCompare a _)

/- ---------------------------- -/
/- unbounded fixed point       -/
/- --------------------------- -/
/- Is NOT supported by the coq backend! -/

 partial def leastFixedPointUnbounded {a : Type} [SetType a] (f : Pset a → Pset a) (x : Pset a) : Pset a :=
   let fx := f x;
   lem_if (setSubsetBy (@setElemCompare a _) fx x) then x
    else leastFixedPointUnbounded f ((setUnionBy (@setElemCompare a _) fx x))
end Lem_Set_extra
